# Generated by Django 5.2.1 on 2025-05-15 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0003_appointment_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
