# Generated by Django 5.2.1 on 2025-05-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0005_alter_userinfor_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dose_schedule',
        ),
        migrations.AddField(
            model_name='appointment',
            name='vaccine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaxcareapp.vaccines'),
            preserve_default=False,
        ),
    ]
