# Generated by Django 5.2.1 on 2025-05-18 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0006_remove_appointment_dose_schedule_appointment_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecords',
            name='health_note',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
