# Generated by Django 5.2.1 on 2025-05-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0008_appointmentdetail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentdetail',
            unique_together={('appointment', 'schedule')},
        ),
        migrations.RemoveField(
            model_name='appointmentdetail',
            name='user',
        ),
    ]
