# Generated by Django 5.2.1 on 2025-05-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0009_alter_appointmentdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Citizen', 'Citizen')], default='Citizen', max_length=20),
        ),
    ]
