# Generated by Django 5.2.1 on 2025-05-27 02:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0011_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
