# Generated by Django 5.2.1 on 2025-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0013_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
