# Generated by Django 5.2.1 on 2025-06-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaxcareapp', '0015_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gmail',
        ),
    ]
